# This is a basic workflow to help you get started with Actions

name: Release WildFly S2I Images to Quay.io

env:
  REGISTRY: quay.io
  REGISTRY_USER: "jmesnil"
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

# Controls when the action will run. 
on:
  release:
    types:
    - published

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup CEKit (Container Evolution Kit)
        uses: manusa/actions-setup-cekit@v1.1.1
        with:
          # Version of CEKit to install
          version: 3.2.1
      # Runs a single command using the runners shell
      - name: Docker Login to Quay.io (master only)
        uses: docker/login-action@v1.8.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
      - name: Build and Push Image Tag
        run: TAG=${GITHUB_REF##*/} make push
